### PR TITLE
Gt 16921 derektor

### PR DESCRIPTION
**Pull request by rundmt**
ListActions: Disabled State is Triggered via 5way

Enyo-DCO-1.1-Signed-off-by: Derek Tor <derek.tor@lge.com>

### CODE REVIEW

**Comment by tomsem** [comment]
webOS ran successfully, Chrome is failing with latest versions, passes with earlier ones

**Comment by webOS101** [comment]
fails on TV, branch conflicts.

**Comment by rundmt** [comment]
I fixed the branch conflict. My TV is acting up so I cannot currently test on TV. But I know it was working as noted in Tom's comment.

**Comment by rundmt** [comment]
So I just tested on my TV and the test seems to be working.

**Pull request closed without merging**
