### PR TITLE
Added files and tests for GT-15937

### PR DESCRIPTION
**Pull request by rundmt**
Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com

### CODE REVIEW

**Comment by rundmt** [comment]
made changes to the test to check for when the picker closes.

**Comment by webOS101** [comment]
Works in Chrome, not on TV.

**Comment by rundmt** [comment]
It appears that the first spotlight down is not responding on webOS. I'll look into the driver and figure out what's going on.

**Comment by rundmt** [comment]
After some investigation I think the issue is related to this https://jira2.lgsvl.com/browse/PLAT-6054. This issue is in the input generator itself.

Some thing weird happens when you start using the key events after using mouse events. The first keypress seems to get rid of the mouse, but it doesn't perform the action. So that leads to 'Thursday' being clicked on webOS and  'Friday' being click on chrome. 

I'll see if there's a way to throw a dummy event in on the TV Driver if the event sequence starts moves from mouse to keys.

**Comment by rundmt** [comment]
So I tried to add a dummy event in the TV Driver but it gives me an error `Unexpected data in simpleCallback.` That basically means you can't send too many events at one given time. I tried a few things and no luck. So my last resort is to create a conditional test case for webOS. I don't know if this is the route we want to go down, but it's the only thing that I can get working because of the Input Generator bug.

**Comment by rundmt** [comment]
Need to use new tvdriver before using. https://gpro.lgsvl.com/#/c/120446/

**Comment by rundmt** [comment]
TVdriver fixes the need to check for webOS

**Pull request merged**
