### PR TITLE
2.6 gt 14597 derektor

### PR DESCRIPTION
**Pull request by rundmt**
Enyo-DCO-1.1-Signed-off-by: Derek Tor derek.tor@lge.com

### CODE REVIEW

**Comment by rundmt** [comment]
Added back getVisibleScrollerText() to the test.

**Comment by webOS101** [comment]
Did you test this again after you added that back?  The test fails for me.  You will need to update the code to be module-aware.   `enyo.$` will now be `dispatcher.$`, which you may have known.

**Comment by rundmt** [comment]
I made that change. Is there some where I'm missing it? A quick search I can't find any enyo.$

**Comment by webOS101** [comment]
OK, well, I fail at reading diffs.  You did update that.

**Comment by rundmt** [comment]
I just tested this on my TV and it seems to work. Elements are clicking for me. Are you still experiencing trouble with this test?

**Comment by webOS101** [comment]
This appears to be a timing issue.  I don't always fail.

**Pull request merged**
